"on":
    push:
        branches:
            - main
name: Deploy to n8n
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply -f ./n8n/porter/porter.yaml
              env:
                PORTER_APP_NAME: n8n
                PORTER_CLUSTER: "4687"
                PORTER_DEPLOYMENT_TARGET_ID: 85ae30bc-d0b1-4c48-97c2-e0761623f955
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "15158"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_15158_4687 }}
